version: '3.8'

services:
  # PostgreSQL 數據庫
  postgres:
    image: postgres:13
    container_name: seniorcareplus-postgres
    environment:
      POSTGRES_DB: seniorcareplus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - seniorcareplus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: seniorcareplus-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - seniorcareplus-network
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health check' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SeniorCarePlus Backend 應用
  backend:
    build: .
    container_name: seniorcareplus-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/seniorcareplus
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - MQTT_BROKER=tcp://mosquitto:1883
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - seniorcareplus-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis (可選，用於緩存)
  redis:
    image: redis:7-alpine
    container_name: seniorcareplus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - seniorcareplus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana (可選，用於監控)
  grafana:
    image: grafana/grafana:latest
    container_name: seniorcareplus-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - seniorcareplus-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  redis_data:
  grafana_data:

networks:
  seniorcareplus-network:
    driver: bridge